apiVersion: v1
kind: Service
metadata:
  name: logstash-pq
  labels:
      app: logstash-pq-demo
spec:
  type: ClusterIP
  ports:
    - port: 9600
      name: "stats"
      protocol: TCP
      targetPort: 9600
  selector:
    app: logstash-pq-demo