apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: demo
  labels:
    app: logstash-demo
spec:
  type: filebeat
  version: 8.3.2
  config:
    logging.level: debug
    output.logstash:
      hosts:
        - "logstash:5044"
    filebeat.inputs:
      - type: log
        symlinks: true
        paths:
          - /var/log/containers/kube-apiserver*.log
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
      - drop_fields:
          fields: ["message"]
  deployment:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers