---
apiVersion: v1
data:
  logstash.conf: |
    input {
      heartbeat {
        message => '{"message": "hello world"}'
        interval => 1
      }
    }
    filter {
      json {
        source => "message"
      }
    }
    output {
      stdout { codec => dots }
    }
kind: ConfigMap
metadata:
  name: logstash-pipeline
  labels:
    app: ls
---
apiVersion: v1
data:
  logstash.yml: |
    api.http.host: "0.0.0.0"
    # monitoring.cluster_uuid: # YOUR PRODUCTION ES CLUSTER UUID
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app: ls