apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: demo
  labels:
    app: logstash-demo
spec:
  type: filebeat
  version: 8.3.2
  config:
    logging.level: debug
    output.logstash:
      hosts:
        - "logstash:5044"
      ssl.certificate_authorities: ["/usr/share/filebeat/ca.crt"]
      ssl.certificate: "/usr/share/filebeat/client.crt"
      ssl.key: "/usr/share/filebeat/client.key"
      ssl.supported_protocols: "TLSv1.2"
    filebeat.inputs:
      - type: log
        symlinks: true
        paths:
          - /var/log/containers/kube-apiserver*.log
          - /var/log/containers/konnectivity-agent*.log
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
      - drop_fields:
          fields: ["message"]
  deployment:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
              - name: logstash-beats-tls
                mountPath: /usr/share/filebeat/ca.crt
                subPath: ca.crt
              - name: logstash-beats-tls
                mountPath: /usr/share/filebeat/client.key
                subPath: client.key
              - name: logstash-beats-tls
                mountPath: /usr/share/filebeat/client.crt
                subPath: client.crt
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: logstash-beats-tls
            secret:
              secretName: logstash-beats-tls